# Generated by Django 2.0.2 on 2018-03-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('PhoneNumber', models.CharField(max_length=256)),
                ('EmailAddress', models.EmailField(max_length=254)),
            ],
        ),
    ]
