# Generated by Django 2.0.2 on 2018-03-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='EmailAddress',
            new_name='Email',
        ),
    ]
