# Generated by Django 2.0.2 on 2018-03-17 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180317_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='Message',
            field=models.CharField(default=django.utils.timezone.now, max_length=1280),
            preserve_default=False,
        ),
    ]
