# Generated by Django 2.0.2 on 2018-03-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180317_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='formModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('PhoneNumber', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=1280)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
